services:
  ashby-extractor:
    build:
      context: .
    env_file:
      - .env
    environment:
      - API_URL=http://crud-server:8081
    networks:
      - app_net

networks:
  app_net:
    external: true
    name: crud-network
